title: "THIS IS A TITLE"
tagline: "I make music/code"
description: "Personal website from Tr33Bug"
github_username: Tr33Bug
twitter_username: Tr33Bug
baseurl: "/home"
url: "https://tr33bug.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
